### ISSUE TITLE
msgpack Error 

### ISSUE THREAD

**Issue by surya00060** [Lyken17/Efficient-PyTorch#10]
I run into the following error. I am using python 3.5.
Traceback (most recent call last):
File "train.py", line 47, in <module>
    train_dataset = ImageFolderLMDB(traindir, train_transform)
File "/media/folder2lmdb.py", line 32, in __init__
    self.keys = msgpack.loads(txn.get(b'__keys__'))
File "msgpack/_unpacker.pyx", line 209, in msgpack._cmsgpack.unpackb msgpack.exceptions.ExtraData: unpack(b) received extra data.

**Comment by Fangyh09** [comment]
@surya00060, You can try it https://github.com/Fangyh09/Image2LMDB.git which is adapted from this repo.

**Comment by surya00060** [comment]
@Fangyh09  Thanks
